<?php
/*
	Question2Answer (c) Gideon Greenspan
	http://www.question2answer.org/
	Description: ภาษาไทยในไฟล์นี้ถูกแปลโดย https://answer.in.th/
	Author: Thai Language by https://answer.in.th/
	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	More about this license: http://www.question2answer.org/license.php
*/
	return array(
		'block_ip_button' => 'บล็อกที่อยู่ IP',
		'browse_categories' => 'เรียกดูตามหมวดหมู่',
		'captcha_approve_fix' => 'การยืนยันนี้จะหยุดแสดงเมื่อบัญชีของคุณได้รับการอนุมัติ.',
		'captcha_confirm_fix' => 'เพื่อหลีกเลี่ยงการยืนยันนี้ในอนาคตโปรด ^5ยืนยันที่อยู่อีเมลของคุณ^6.',
		'captcha_error' => 'โปรดดำเนินการตรวจสอบการป้องกันสแปม',
		'captcha_label' => 'การตรวจสอบการป้องกันสแปม:',
		'captcha_login_fix' => 'เพื่อหลีกเลี่ยงการยืนยันนี้ในอนาคตโปรด ^1enter^2 หรือ ^3ลงทะเบียน^4.',
		'feed_a_edited_prefix' => 'คำตอบที่แก้ไข: ',
		'feed_a_prefix' => 'ตอบแล้ว: ',
		'feed_a_reshown_prefix' => 'คำตอบปรากฏขึ้นอีกครั้ง: ',
		'feed_a_selected_prefix' => 'คำตอบที่เลือก: ',
		'feedback_email' => 'ที่อยู่อีเมลของคุณ: (ไม่บังคับ)',
		'feedback_empty' => 'โปรดใช้ฟิลด์นี้เพื่อส่งความคิดเห็นหรือข้อเสนอแนะ',
		'feedback_message' => 'ความคิดเห็นหรือข้อเสนอแนะของคุณสำหรับ ^:',
		'feedback_name' => 'ชื่อของคุณ: (ไม่บังคับ) ',
		'feedback_sent' => 'ข้อความของคุณถูกส่งไปแล้วขอบคุณมาก.',
		'feedback_title' => 'ส่งความคิดเห็น',
		'feed_c_edited_prefix' => 'ความคิดเห็นที่แก้ไข: ',
		'feed_closed_prefix' => 'ปิด: ',
		'feed_c_moved_prefix' => 'ย้ายความคิดเห็นแล้ว: ',
		'feed_c_prefix' => 'แสดงความคิดเห็น: ',
		'feed_c_reshown_prefix' => 'แสดงความคิดเห็นอีกครั้ง: ',
		'feed_edited_prefix' => 'แก้ไขแล้ว: ',
		'feed_hidden_prefix' => 'ซ่อนอยู่: ',
		'feed_not_found' => 'ไม่พบ Feed',
		'feed_recategorized_prefix' => 'จัดหมวดหมู่ใหม่: ',
		'feed_reopened_prefix' => 'เปิดใหม่: ',
		'feed_reshown_prefix' => 'แสดงอีกครั้ง: ',
		'feed_retagged_prefix' => 'การติดแท็กใหม่: ',
		'form_security_again' => 'กรุณาคลิกอีกครั้งเพื่อยืนยัน',
		'form_security_reload' => 'โปรดโหลดหน้าเว็บและลองอีกครั้ง',
		'hide_all_ip_button' => 'ซ่อนโพสต์ทั้งหมดจาก IP นี้',
		'host_name' => 'ชื่อโฮสต์:',
		'inbox' => 'กล่องจดหมาย',
		'matches_blocked_ips' => 'ที่อยู่ IP ที่ถูกบล็อก:',
		'message_empty' => 'กรุณากรอกข้อความของคุณเพื่อส่งถึงผู้ใช้รายนี้',
		'message_explanation' => 'สิ่งนี้จะถูกส่งเป็นการแจ้งเตือนจาก ^ ที่อยู่อีเมลของคุณจะไม่ถูกเปิดเผยเว้นแต่คุณจะป้อนในข้อความ.',
		'message_for_x' => 'ข้อความของคุณสำหรับ ^:',
		'message_limit' => 'ส่งข้อความส่วนตัวมากเกินไปโปรดลองอีกครั้งในอีก 1 ชั่วโมง',
		'message_must_login' => 'กรุณา ^1เข้าสู่ระบบ^2 หรือ ^3ลงทะเบียน^4 เพื่อส่งข้อความส่วนตัว.',
		'message_recent_history' => 'การติดต่อล่าสุดกับ ^',
		'message_sent' => 'ส่งข้อความส่วนตัวของคุณแล้ว',
		'more_favorite_qs' => 'คำถามที่ชอบ...',
		'more_favorite_tags' => 'แท็กที่ชอบ...',
		'more_favorite_users' => 'ผู้ใช้งานที่ราชื่นชอบ...',
		'my_favorites_title' => 'รายการโปรดของฉัน',
		'nav_all_my_updates' => 'การอัปเดตทั้งหมดของฉัน',
		'nav_my_content' => 'เนื้อหาของฉัน',
		'nav_my_details' => 'บัญชีของฉัน',
		'nav_my_favorites' => 'รายการโปรดของฉัน',
		'nav_user_activity' => 'กิจกรรมล่าสุด',
		'nav_user_as' => 'คำตอบทั้งหมด',
		'nav_user_pms' => 'ข้อความส่วนตัว',
		'nav_user_qs' => 'คำถามทั้งหมด',
		'nav_user_wall' => 'หน้าวอลล์',
		'next_step' => 'ต่อไป',
		'no_activity_from_x' => 'ไม่มีกิจกรรมใน ^',
		'no_favorite_categories' => 'ไม่มีหมวดหมู่ที่ถูกใจ',
		'no_favorite_qs' => 'ไม่มีคำถามที่ถูกใจ',
		'no_favorite_tags' => 'ไม่มีแท็กที่ถูกใจ',
		'no_favorite_users' => 'ไม่มีผู้ใช้ที่ถูกใจ',
		'no_recent_updates' => 'ไม่มีการอัปเดตล่าสุด',
		'no_updates_content' => 'ไม่มีการอัปเดตล่าสุดสำหรับเนื้อหาของฉัน',
		'no_updates_favorites' => 'ไม่มีการอัปเดตรายการโปรดของฉัน',
		'outbox' => 'ข้อความที่ส่ง',
		'private_message_title' => 'ส่งข้อความส่วนตัว',
		'pm_inbox_title' => 'ได้รับข้อความส่วนตัว',
		'pm_outbox_title' => 'ข้อความส่วนตัวที่ส่งแล้ว',
		'recent_activity_from_x' => 'กิจกรรมล่าสุดใน ^',
		'recent_updates_content' => 'การอัปเดตล่าสุดสำหรับเนื้อหาของฉัน',
		'recent_updates_favorites' => 'การอัปเดตล่าสุดในรายการโปรดของฉัน',
		'recent_updates_title' => 'อัปเดตล่าสุด',
		'site_in_maintenance' => 'เว็บไซต์นี้อยู่ระหว่างการบำรุงรักษา - โปรดลองเข้าใช้งานในภายหลัง.',
		'suggest_favorites_add' => 'หากต้องการเพิ่มคำถามหรือรายการอื่น ๆ ในรายการโปรดของคุณให้คลิก ^ ที่ด้านบนสุดของหน้า.',
		'suggest_update_favorites' => 'หากต้องการอัปเดตเพิ่มเติมให้เพิ่มรายการใน ^1รายการโปรดของคุณ^2.',
		'unblock_ip_button' => 'เลิกบล็อกที่อยู่ IP',
		'your_a_commented' => 'คำตอบของคุณได้รับความคิดเห็น',
		'your_a_edited' => 'คำตอบที่คุณแก้ไข',
		'your_a_hidden' => 'คำตอบที่ซ่อนอยู่ของคุณ',
		'your_a_questioned' => 'มีคำถามในคำตอบของคุณ',
		'your_a_reshown' => 'คำตอบของคุณปรากฏขึ้นอีกครั้ง',
		'your_a_selected' => 'คำตอบที่คุณเลือก',
		'your_c_edited' => 'ความคิดเห็นที่คุณแก้ไข',
		'your_c_followed' => 'ความคิดเห็นของคุณ ติดตาม',
		'your_c_hidden' => 'ความคิดเห็นที่ซ่อนอยู่ของคุณ',
		'your_c_moved' => 'ความคิดเห็นของคุณถูกย้าย',
		'your_c_reshown' => 'ความคิดเห็นของคุณปรากฏขึ้นอีกครั้ง',
		'your_q_answered' => 'คำถามของคุณได้รับคำตอบ',
		'your_q_closed' => 'คำถามของคุณถูกปิดแล้ว',
		'your_q_commented' => 'คำถามของคุณ มีการแสดงความคิดเห็น',
		'your_q_edited' => 'คำถามของคุณแก้ไขแล้ว',
		'your_q_hidden' => 'คำถามที่ซ่อนอยู่ของคุณ',
		'your_q_recategorized' => 'คำถามของคุณถูกจัดหมวดหมู่ใหม่',
		'your_q_reopened' => 'คำถามของคุณถูกเปิดขึ้นมาใหม่',
		'your_q_reshown' => 'คำถามของคุณปรากฏขึ้นอีกครั้ง',
		'your_q_retagged' => 'คำถามของคุณระบุแท็กใหม่',
	);