<?php
/*
	Question2Answer (c) Gideon Greenspan
	http://www.question2answer.org/
	Description: ภาษาไทยในไฟล์นี้ถูกแปลโดย https://answer.in.th/
	Author: Thai Language by https://answer.in.th/
	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	More about this license: http://www.question2answer.org/license.php
*/
	return array(
		'about' => 'เกี่ยวกับฉัน',
		'add_user_x_favorites' => 'เพิ่มผู้ใช้ ชื่อ User : ^ ในรายการโปรดของฉัน',
		'approved_user' => 'ผู้ใช้ที่ได้รับการอนุมัติ',
		'approve_required' => 'โปรดรอให้บัญชีของคุณได้รับการอนุมัติหรือ ^1เพิ่มข้อมูลเพิ่มเติม^2.',  // @deprecated
		'approve_title' => 'อยู่ระหว่างการอนุมัติของผู้ใช้',
		'approve_user_button' => 'อนุมัติผู้ใช้',
		'avatar_default' => 'ค่าเริ่มต้น',
		'avatar_gravatar' => 'แสดง ^1Gravatar^2 ของฉัน',
		'avatar_label' => 'รูปประวัติ:',
		'avatar_none' => 'ไม่มี',
		'blocked_users' => 'ผู้ใช้ที่ถูกบล็อก',
		'block_user_button' => 'บล็อกผู้ใช้',
		'category_level_add' => ' - ^1เพิ่มสิทธิ์เฉพาะหมวดหมู่^2',
		'category_level_in' => 'สำหรับหมวดหมู่ถัดไป:',
		'category_level_label' => 'อัปเดตเป็น:',
		'category_level_none' => 'ไม่มีการอัปเดต',
		'change_email_link' => ' - ^1เปลี่ยนอีเมล^2',
		'change_password' => 'เปลี่ยนรหัสผ่าน',
		'confirm_button' => 'ยืนยันที่อยู่อีเมล',
		'confirm_complete' => 'ขอบคุณมาก - ที่อยู่อีเมลของคุณได้รับการยืนยันแล้ว',
		'confirm_emailed' => 'ส่งอีเมลยืนยันถึงคุณแล้ว (หากไม่พบดูที่จดหมายขยะ) กรุณาคลิกลิงก์เพื่อยืนยันที่อยู่อีเมลของคุณ หรือป้อนรหัสยืนยันด้านล่าง.',
		'confirm_required' => 'ในการลงทะเบียนให้เสร็จสมบูรณ์ให้คลิกที่ลิงค์ยืนยันที่เราส่งให้คุณทางอีเมล (หากไม่พบเมลกรุณาตรวจสอบที่ "จดหมายขยะ")   หรือ ^1ส่งเมล์ยืนยันอีกครั้ง^2.',
		'confirm_title' => 'การยืนยันที่อยู่อีเมล',
		'confirm_wrong_log_in' => 'รหัสไม่ถูกต้อง - โปรด ^1เข้าสู่ระบบ^2 เพื่อส่งลิงค์ใหม่',
		'confirm_wrong_resend' => 'รหัสไม่ถูกต้อง - โปรดคลิกลิงก์ด้านล่างเพื่อส่งลิงก์ใหม่',
		'delete_user_button' => 'ลบผู้ใช้',
		'edit_profile' => 'แก้ไขโปรไฟล์ของฉัน',
		'edit_user_button' => 'แก้ไขผู้ใช้นี้',
		'email_code_another' => 'ส่งอีก',
		'email_code_emailed' => 'รหัสของคุณถูกส่งถึงคุณแล้ว',
		'email_code_label' => 'รหัส:',
		'email_code_wrong' => 'รหัสไม่ถูกต้อง',
		'email_confirmed' => 'ได้รับการยืนยัน',
		'email_exists' => 'ที่อยู่อีเมลนี้เป็นของบัญชีอยู่แล้ว',
		'email_handle_label' => 'อีเมล์หรือชื่อผู้ใช้:',
		'email_invalid' => 'ที่อยู่อีเมลไม่ถูกต้องโปรดตรวจสอบอย่างละเอียด',
		'email_label' => 'อีเมล์:',
		'email_not_confirmed' => 'อีเมล์ยังไม่ได้รับการยืนยัน',
		'email_please_confirm' => 'กรุณา ^5ยืนยัน^6',
		'email_required' => 'ต้องระบุอีเมล - เราไม่แสดงต่อสาธารณะ',
		'forgot_link' => 'ฉันลืมรหัสผ่าน',
		'full_name' => 'ชื่อเต็ม',
		'handle_blocked' => 'ไม่อนุญาตให้ใช้ชื่อผู้ใช้นี้ โปรดลองชื่ออื่น',
		'handle_empty' => 'ชื่อผู้ใช้ต้องไม่ว่างเปล่า',
		'handle_exists' => 'มีการใช้ชื่อผู้ใช้นี้แล้ว โปรดลองชื่ออื่น',
		'handle_has_bad' => 'ชื่อผู้ใช้ไม่สามารถมีคำนี้ได้: ^',
		'handle_label' => 'ชื่อผู้ใช้:',
		'hide_all_user_button' => 'ซ่อนโพสต์จากผู้ใช้รายนี้',
		'last_login_label' => 'การเข้าครั้งสุดท้าย:',
		'last_write_label' => 'โพสต์ล่าสุด:',
		'level_admin' => 'ผู้ดูแลระบบ',
		'level_editor' => 'นักแก้ไข',
		'level_expert' => 'ผู้เชี่ยวชาญ',
		'level_for_category' => '^1 โดย ^2',
		'level_in_general' => 'สมาชิกทั่วไป',
		'level_moderator' => 'โมเดอเรเตอร์',
		'level_super' => 'ซุปเปอร์แอดมิน',
		'location' => 'สถานที่',
		'login_button' => 'เข้าสู่ระบบ',
		'login_limit' => 'พยายามเข้าสู่ระบบมากเกินไปโปรดลองอีกครั้งในอีก 1 ชั่วโมง',
		'login_title' => 'เข้าสู่ระบบ Answer.in.th',
		'log_in_to_access' => 'ตอนนี้คุณต้อง ^1เข้าสู่ระบบ^2 เพื่อเข้าถึงบัญชีของคุณ.',
		'mass_mailings' => 'อีเมลจำนวนมาก:',
		'mass_mailings_explanation' => 'สมัครรับอีเมลที่ส่งถึงผู้ใช้ทุกคน',
		'member_for' => 'เป็นสมาชิกตั้งแต่:',
		'member_type' => 'สมาชิกระดับ:',
		'new_password_1' => 'รหัสผ่านใหม่:',
		'new_password_2' => 'ระบุรหัสผ่านใหม่อีกครั้ง:',
		'no_blocked_users' => 'ไม่พบผู้ใช้ที่ถูกบล็อก',
		'no_permission' => 'คุณไม่ได้รับอนุญาตให้ดำเนินการนี้',
		'old_password' => 'รหัสผ่านเก่า:',
		'only_shown_admins' => '(แสดงต่อผู้ดูแลระบบเท่านั้น)',
		'only_shown_editors' => '(แสดงเฉพาะผู้แก้ไขหรือระดับที่สูงกว่า )',
		'only_shown_experts' => '(แสดงเฉพาะผู้เชี่ยวชาญหรือระดับสูงกว่า)',
		'only_shown_moderators' => '(แสดงเฉพาะกับโมเดอเรเตอร์เท่านั้น)',
		'password_changed' => 'เปลี่ยนรหัสผ่านแล้ว',
		'password_label' => 'รหัสผ่าน:',
		'password_min' => 'รหัสผ่านต้องมีอย่างน้อย ^ อักขระ',
		'password_mismatch' => 'รหัสผ่านใหม่ไม่ตรงกัน',
		'password_none' => 'ไม่มีรหัสผ่าน. หากต้องการป้อนโดยตรงให้กำหนดรหัสผ่านด้านล่าง.',
		'password_sent' => 'รหัสผ่านใหม่ของคุณถูกส่งไปทางอีเมล',
		'password_to_set' => 'โปรดกำหนดค่าในหน้าบัญชีของคุณ',
		'password_wrong' => 'รหัสผ่านไม่ถูกต้อง',
		'private_messages_explanation' => 'อนุญาตให้ผู้ใช้ส่งอีเมลถึงฉัน (โดยไม่เห็นที่อยู่ของฉัน)',
		'private_messages' => 'ข้อความส่วนตัว:',
		'profile_saved' => 'บันทึกโปรไฟล์แล้ว',
		'register_button' => 'ลงทะเบียน',
		'registered_label' => 'ลงทะเบียน:',
		'registered_user' => 'ผู้ใช้ที่ลงทะเบียน',
		'register_limit' => 'มีการลงทะเบียนจำนวนมาก - โปรดลองอีกครั้งในอีกหนึ่งชั่วโมง',
		'register_suspended' => 'ระบบการลงทะเบียนผู้ใช้ใหม่ถูกปิดใช้งานชั่วคราว กรุณาลองใหม่อีกครั้งในภายหลัง.',
		'register_title' => 'ลงทะเบียนเป็นผู้ใช้ใหม่',
		'remember_label' => 'จดจำฉันในคอมพิวเตอร์เครื่องนี้',
		'remember' => 'จดจำ',
		'remove_avatar' => 'ลบรูปประจำตัว:',
		'reset_title' => 'รีเซ็ตรหัสผ่านที่ลืม',
		'save_profile' => 'จัดเก็บรายละเอียด',
		'save_user' => 'บันทึกผู้ใช้',
		'send_confirm_button' => 'ส่งลิงค์ยืนยัน',
		'send_reset_button' => 'ส่งอีเมลเพื่อรีเซ็ตรหัสผ่าน',
		'send_reset_note' => 'ข้อความพร้อมคำแนะนำจะถูกส่งไปยังที่อยู่อีเมลของคุณ.',
		'special_users' => 'ผู้ใช้พิเศษ',
		'terms_not_accepted' => 'คุณต้องตรวจสอบสิ่งนี้.',
		'unblock_user_button' => 'ปลดล็อกผู้ใช้',
		'unsubscribe_complete' => 'คุณถูกยกเลิกการสมัครรับอีเมลจำนวนมากที่ ^0 ส่งมา คุณสามารถสมัครใหม่ได้ตลอดเวลาจากบัญชี ^1ของคุณ^2.',
		'unsubscribe' => 'ยกเลิกการสมัคร:',
		'unsubscribe_title' => 'ยกเลิกการสมัคร',
		'unsubscribe_wrong_log_in' => 'รหัสไม่ถูกต้อง - โปรด ^1เข้าสู่ระบบ^2 เพื่อยกเลิกการสมัคร',
		'user_blocked' => '(บล็อก)',
		'user_not_found' => 'ไม่พบชื่อผู้ใช้',
		'wall_posts_explanation' => 'อนุญาตให้ผู้ใช้รายอื่นโพสต์บนวอลล์ของคุณ (คุณจะได้รับอีเมลด้วย)',
		'wall_posts' => 'กระทู้บนวอลล์:',
		'website' => 'เวบไซต์',
		'x_ago_from_y' => 'ทำ ^1 ตั้งแต่ ^2',
	);